echo "--- Executing initialization force file for ../testcode/mp21-cp.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
echo "Initializing the processor."
force /start_h 0 @0
force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/mp21-cp.asm program code."
run 5
change /mp2_cpu/dram/vhdl_memory/mem(0) X"3B"
change /mp2_cpu/dram/vhdl_memory/mem(1) X"E0"
change /mp2_cpu/dram/vhdl_memory/mem(2) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(3) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(4) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(5) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(6) X"36"
change /mp2_cpu/dram/vhdl_memory/mem(7) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(8) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(9) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(10) X"34"
change /mp2_cpu/dram/vhdl_memory/mem(11) X"06"
change /mp2_cpu/dram/vhdl_memory/mem(12) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(13) X"92"
change /mp2_cpu/dram/vhdl_memory/mem(14) X"32"
change /mp2_cpu/dram/vhdl_memory/mem(15) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(16) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(17) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(18) X"64"
change /mp2_cpu/dram/vhdl_memory/mem(19) X"D2"
change /mp2_cpu/dram/vhdl_memory/mem(20) X"71"
change /mp2_cpu/dram/vhdl_memory/mem(21) X"D2"
change /mp2_cpu/dram/vhdl_memory/mem(22) X"2E"
change /mp2_cpu/dram/vhdl_memory/mem(23) X"06"
change /mp2_cpu/dram/vhdl_memory/mem(24) X"51"
change /mp2_cpu/dram/vhdl_memory/mem(25) X"D2"
change /mp2_cpu/dram/vhdl_memory/mem(26) X"2C"
change /mp2_cpu/dram/vhdl_memory/mem(27) X"0C"
change /mp2_cpu/dram/vhdl_memory/mem(28) X"60"
change /mp2_cpu/dram/vhdl_memory/mem(29) X"52"
change /mp2_cpu/dram/vhdl_memory/mem(30) X"2A"
change /mp2_cpu/dram/vhdl_memory/mem(31) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(32) X"1C"
change /mp2_cpu/dram/vhdl_memory/mem(33) X"E4"
change /mp2_cpu/dram/vhdl_memory/mem(34) X"80"
change /mp2_cpu/dram/vhdl_memory/mem(35) X"C0"
change /mp2_cpu/dram/vhdl_memory/mem(36) X"27"
change /mp2_cpu/dram/vhdl_memory/mem(37) X"0E"
change /mp2_cpu/dram/vhdl_memory/mem(38) X"1A"
change /mp2_cpu/dram/vhdl_memory/mem(39) X"22"
change /mp2_cpu/dram/vhdl_memory/mem(40) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(41) X"94"
change /mp2_cpu/dram/vhdl_memory/mem(42) X"A1"
change /mp2_cpu/dram/vhdl_memory/mem(43) X"14"
change /mp2_cpu/dram/vhdl_memory/mem(44) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(45) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(46) X"22"
change /mp2_cpu/dram/vhdl_memory/mem(47) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(48) X"0B"
change /mp2_cpu/dram/vhdl_memory/mem(49) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(50) X"04"
change /mp2_cpu/dram/vhdl_memory/mem(51) X"72"
change /mp2_cpu/dram/vhdl_memory/mem(52) X"0D"
change /mp2_cpu/dram/vhdl_memory/mem(53) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(54) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(55) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(56) X"08"
change /mp2_cpu/dram/vhdl_memory/mem(57) X"32"
change /mp2_cpu/dram/vhdl_memory/mem(58) X"04"
change /mp2_cpu/dram/vhdl_memory/mem(59) X"64"
change /mp2_cpu/dram/vhdl_memory/mem(60) X"0E"
change /mp2_cpu/dram/vhdl_memory/mem(61) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(62) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(63) X"92"
change /mp2_cpu/dram/vhdl_memory/mem(64) X"61"
change /mp2_cpu/dram/vhdl_memory/mem(65) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(66) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(67) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(68) X"17"
change /mp2_cpu/dram/vhdl_memory/mem(69) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(70) X"C0"
change /mp2_cpu/dram/vhdl_memory/mem(71) X"C1"
change /mp2_cpu/dram/vhdl_memory/mem(72) X"15"
change /mp2_cpu/dram/vhdl_memory/mem(73) X"0E"
change /mp2_cpu/dram/vhdl_memory/mem(74) X"0B"
change /mp2_cpu/dram/vhdl_memory/mem(75) X"62"
change /mp2_cpu/dram/vhdl_memory/mem(76) X"08"
change /mp2_cpu/dram/vhdl_memory/mem(77) X"B2"
change /mp2_cpu/dram/vhdl_memory/mem(78) X"07"
change /mp2_cpu/dram/vhdl_memory/mem(79) X"64"
change /mp2_cpu/dram/vhdl_memory/mem(80) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(81) X"92"
change /mp2_cpu/dram/vhdl_memory/mem(82) X"61"
change /mp2_cpu/dram/vhdl_memory/mem(83) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(84) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(85) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(86) X"0E"
change /mp2_cpu/dram/vhdl_memory/mem(87) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(88) X"C0"
change /mp2_cpu/dram/vhdl_memory/mem(89) X"C1"
change /mp2_cpu/dram/vhdl_memory/mem(90) X"0C"
change /mp2_cpu/dram/vhdl_memory/mem(91) X"A2"
change /mp2_cpu/dram/vhdl_memory/mem(92) X"0B"
change /mp2_cpu/dram/vhdl_memory/mem(93) X"0C"
change /mp2_cpu/dram/vhdl_memory/mem(94) X"0B"
change /mp2_cpu/dram/vhdl_memory/mem(95) X"64"
change /mp2_cpu/dram/vhdl_memory/mem(96) X"BF"
change /mp2_cpu/dram/vhdl_memory/mem(97) X"94"
change /mp2_cpu/dram/vhdl_memory/mem(98) X"A1"
change /mp2_cpu/dram/vhdl_memory/mem(99) X"14"
change /mp2_cpu/dram/vhdl_memory/mem(100) X"42"
change /mp2_cpu/dram/vhdl_memory/mem(101) X"12"
change /mp2_cpu/dram/vhdl_memory/mem(102) X"06"
change /mp2_cpu/dram/vhdl_memory/mem(103) X"0A"
change /mp2_cpu/dram/vhdl_memory/mem(104) X"DE"
change /mp2_cpu/dram/vhdl_memory/mem(105) X"4F"
change /mp2_cpu/dram/vhdl_memory/mem(106) X"EF"
change /mp2_cpu/dram/vhdl_memory/mem(107) X"E5"
change /mp2_cpu/dram/vhdl_memory/mem(108) X"80"
change /mp2_cpu/dram/vhdl_memory/mem(109) X"40"
change /mp2_cpu/dram/vhdl_memory/mem(110) X"4B"
change /mp2_cpu/dram/vhdl_memory/mem(111) X"F0"
change /mp2_cpu/dram/vhdl_memory/mem(112) X"05"
change /mp2_cpu/dram/vhdl_memory/mem(113) X"19"
change /mp2_cpu/dram/vhdl_memory/mem(114) X"01"
change /mp2_cpu/dram/vhdl_memory/mem(115) X"04"
change /mp2_cpu/dram/vhdl_memory/mem(116) X"FF"
change /mp2_cpu/dram/vhdl_memory/mem(117) X"0F"
change /mp2_cpu/dram/vhdl_memory/mem(118) X"FF"
change /mp2_cpu/dram/vhdl_memory/mem(119) X"0F"
change /mp2_cpu/dram/vhdl_memory/mem(120) X"01"
change /mp2_cpu/dram/vhdl_memory/mem(121) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(122) X"20"
change /mp2_cpu/dram/vhdl_memory/mem(123) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(124) X"D5"
change /mp2_cpu/dram/vhdl_memory/mem(125) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(126) X"0F"
change /mp2_cpu/dram/vhdl_memory/mem(127) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(136) X"86"
change /mp2_cpu/dram/vhdl_memory/mem(137) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(138) X"0D"
change /mp2_cpu/dram/vhdl_memory/mem(139) X"60"
change /mp2_cpu/dram/vhdl_memory/mem(140) X"DD"
change /mp2_cpu/dram/vhdl_memory/mem(141) X"BA"
change /mp2_cpu/dram/vhdl_memory/mem(142) X"37"
change /mp2_cpu/dram/vhdl_memory/mem(143) X"13"
change /mp2_cpu/dram/vhdl_memory/mem(144) X"8E"
change /mp2_cpu/dram/vhdl_memory/mem(145) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(146) X"FF"
change /mp2_cpu/dram/vhdl_memory/mem(147) X"FF"
change /mp2_cpu/dram/vhdl_memory/mem(148) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(149) X"13"
change /mp2_cpu/dram/vhdl_memory/mem(150) X"98"
change /mp2_cpu/dram/vhdl_memory/mem(151) X"00"
change /mp2_cpu/dram/vhdl_memory/mem(152) X"09"
change /mp2_cpu/dram/vhdl_memory/mem(153) X"6A"
change /mp2_cpu/dram/vhdl_memory/mem(154) X"7F"
change /mp2_cpu/dram/vhdl_memory/mem(155) X"99"
change /mp2_cpu/dram/vhdl_memory/mem(156) X"21"
change /mp2_cpu/dram/vhdl_memory/mem(157) X"19"
change /mp2_cpu/dram/vhdl_memory/mem(158) X"C0"
change /mp2_cpu/dram/vhdl_memory/mem(159) X"C1"
run 5
echo "Done loading ../testcode/mp21-cp.asm program code."
