-- VHDL Entity ece411.StoreMux.generatedInstance
--
-- Created:
--          by - page10.ews (linux6.ews.illinois.edu)
--          at - 21:51:54 01/21/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

ENTITY StoreMux IS
   PORT( 
      dest        : IN     LC3b_word (15 DOWNTO 0);
      SrcA        : IN     LC3b_word (15 DOWNTO 0);
      StoreMuxout : OUT    LC3b_word (15 DOWNTO 0);
      StoreSR     : IN     std_logic
   );

END StoreMux ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF StoreMux IS 
BEGIN


END generatedInstance;
